# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: riuson.acl::lang.backend_group.record_name_group

# Model Form Field configuration
form: $/riuson/acl/models/group/fields.yaml

# Model Class name
modelClass: Riuson\ACL\Models\Group

# Default redirect location
defaultRedirect: riuson/acl/groups

# Create page
create:
    title: riuson.acl::lang.backend_group.create_group
    redirect: riuson/acl/groups/update/:id
    redirectClose: riuson/acl/groups

# Update page
update:
    title: riuson.acl::lang.backend_group.edit_group
    redirect: riuson/acl/groups
    redirectClose: riuson/acl/groups

# Preview page
preview:
    title: riuson.acl::lang.backend_group.preview_group