# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Permission

# Model Form Field configuration
form: $/riuson/acl/models/permission/fields.yaml

# Model Class name
modelClass: Riuson\ACL\Models\Permission

# Default redirect location
defaultRedirect: riuson/acl/permissions

# Create page
create:
    title: Create Permission
    redirect: riuson/acl/permissions/update/:id
    redirectClose: riuson/acl/permissions

# Update page
update:
    title: Edit Permission
    redirect: riuson/acl/permissions
    redirectClose: riuson/acl/permissions

# Preview page
preview:
    title: Preview Permission